# -*- coding: utf-8 -*-
"""RNA no Orange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zW2t1MzPn2U63P4qLiNz8KS6QwF9nFsy
"""

!pip install Orange3

import Orange
import pickle

model = pickle.load(open("model.pkcls", "rb"))
print(model)